#' @title R wrapper to Run stringtie
#' @description Run stringtie for transcriptome assembly 
#' @param bam Character, BAM file (sorted by genomic coordinates)
#' @param reference Character, reference annotation GTF (optional)
#' @param outfile Character, output GTF file name
#' @param params Character, extra parameters (default "")
#' @param longRead Logical, whether the data is long-read (PacBio/ONT). Default FALSE (short-read).

#'
#' @export
stringtieAssembly <- function(bam, reference = NULL, outfile, params = "", longRead = FALSE) {
  if (!all(file.exists(bam))) stop("BAM file not found: ", bam)
  
  args <- c(bam)
  
  if (longRead) {
    args <- c(args, "-L")
  }
  

  if (!is.null(reference)) {
    args <- c(args, "-G", reference)
  }
  
  args <- c(args, "-o", outfile)
  

  if (nzchar(params)) {
    args <- c(args, strsplit(params, "\\s+")[[1]])
  }

  if (longRead) {
    rc <- .Stringtiebin3(paste(args, collapse = " "))
  } else {
    rc <- .Stringtiebin(paste(args, collapse = " "))
  }
  
  invisible(rc)
}

#' @title R wrapper to Run stringtie tool
#' @description Merge transcripts
#'
#' @param reference Use a reference annotation file to guide assembly process
#' @param gtfFiles Character, GTF files assembled from transcripts by stringtie
#' @param outfile Character, the output of the merged GTF
#' @param params Other parameters
#' @export
stringtieMerge <- function(reference, gtfFiles, outfile, params = "") {
  if (!all(file.exists(gtfFiles))) {
    stop("Some GTF files do not exist.")
  }
  
  outdir <- dirname(outfile)
  if (!dir.exists(outdir)) {
    dir.create(outdir, recursive = TRUE, showWarnings = FALSE)
  }
  
  if (file.exists(outfile)) {
    warning("Existing outfile will be overwritten: ", outfile)
    unlink(outfile)
  }
  
  before <- list.files(outdir, pattern = "\\.gtf$", full.names = TRUE)
  
  programtags <- "--merge"
  reference <- paste("-G", reference, sep = " ")
  gtffile <- paste(gtfFiles, collapse = " ")
  outfile_arg <- paste("-o", outfile, sep = " ")
  cmd <- sprintf("%s %s %s %s %s", programtags, reference, gtffile, outfile_arg, params)
  
  rc <- .Stringtiebin(cmd)
  
  if (!file.exists(outfile)) {
    after <- list.files(outdir, pattern = "\\.gtf$", full.names = TRUE)
    new_gtf <- setdiff(after, before)
    
    if (length(new_gtf) >= 1) {
      newest <- new_gtf[which.max(file.info(new_gtf)$mtime)]
      ok <- file.rename(newest, outfile)
      
      if (!ok || !file.exists(outfile)) {
        stop("Failed to rename merged GTF to expected outfile: ", outfile)
      }
    } else {
      stop("Expected merged GTF not found: ", outfile)
    }
  }
  
  invisible(rc)
}


#' @title R wrapper to run gffcompare
#' @description The function to compare one or more GTF/GFF files (the query files)
#' with a reference annotation using gffcompare. The final annotated GTF is renamed
#' to the user-specified `outfile`. Tracking, loci and summary files are retained,
#' while temporary `.tmap` and `.refmap` files are removed by default.
#' @param reference Use a reference annotation file to guide compare assembly process.
#' @param gtffile GTF/GFF file(s) with assembled transcripts.
#' @param outfile The name of the final output annotated GTF.
#' @param params Other parameters passed to gffcompare.
#' @param cleanup Logical. Whether to remove `.tmap` and `.refmap` files generated by gffcompare. Default is TRUE.
#' @param overwrite Logical. Whether to overwrite existing output files. Default is FALSE.
#' @export


gffcompareAnno <- function(reference, gtffile, outfile, params = "",
                           cleanup = TRUE, overwrite = FALSE) {
  if (!all(file.exists(gtffile))) {
    stop("Some GTF files do not exist.")
  }
  
  outdir <- dirname(outfile)
  if (!dir.exists(outdir)) {
    dir.create(outdir, recursive = TRUE, showWarnings = FALSE)
  }
  
  outbase <- tools::file_path_sans_ext(basename(outfile))
  final_prefix <- file.path(outdir, outbase)
  
  final_files <- c(
    outfile,
    paste0(final_prefix, ".tracking"),
    paste0(final_prefix, ".loci"),
    final_prefix
  )
  
  existing <- final_files[file.exists(final_files)]
  if (length(existing) > 0 && !overwrite) {
    stop(
      "Output file(s) already exist: ",
      paste(existing, collapse = ", "),
      "\nSet overwrite = TRUE to replace them."
    )
  }
  if (length(existing) > 0 && overwrite) {
    unlink(existing)
  }
  
  tmp_prefix <- file.path(
    outdir,
    paste0(".gffcompare_tmp_", Sys.getpid(), "_", outbase)
  )
  
  reference_arg <- paste("-r", reference)
  outfile_arg <- paste("-o", tmp_prefix)
  gtffile_arg <- paste(gtffile, collapse = " ")
  
  cmd <- sprintf(
    "%s %s %s %s",
    reference_arg,
    outfile_arg,
    gtffile_arg,
    params
  )
  
  rc <- invisible(lapply(cmd, .gffcompareBin))
  
  tmp_annotated <- paste0(tmp_prefix, ".annotated.gtf")
  tmp_tracking  <- paste0(tmp_prefix, ".tracking")
  tmp_loci      <- paste0(tmp_prefix, ".loci")
  tmp_summary   <- tmp_prefix
  
  if (!file.exists(tmp_annotated)) {
    stop("Expected annotated GTF was not generated: ", tmp_annotated)
  }
  
  file.rename(tmp_annotated, outfile)
  
  if (file.exists(tmp_tracking)) {
    file.rename(tmp_tracking, paste0(final_prefix, ".tracking"))
  }
  
  if (file.exists(tmp_loci)) {
    file.rename(tmp_loci, paste0(final_prefix, ".loci"))
  }
  
  if (file.exists(tmp_summary)) {
    file.rename(tmp_summary, final_prefix)
  }
  
  if (cleanup) {
    tmp_files <- list.files(
      outdir,
      pattern = paste0("^", basename(tmp_prefix)),
      full.names = TRUE
    )
    
    remove_files <- tmp_files[
      grepl("\\.(tmap|refmap)$", tmp_files)
    ]
    
    if (length(remove_files) > 0) {
      unlink(remove_files)
    }
  }
  
  invisible(rc)
}


#' @title Preparing the genome annotation object
#' @description Flatten exon appearing multiple times among different transcripts in GTF file
#' @param gtffile GTF file.
#' @param singleGens Whether to allocate the exon overlapping with two genes to a single gene. Default is TRUE.
#' @param transposon A GRanges object with transposon data
#' @param minoverlap Minimum overlap for \code{\link[IRanges]{findOverlaps}}. Default is 10.
#' @param cores Number of cores used for parallel processing. Default is 1.
#' @importFrom BiocParallel bplapply MulticoreParam
#' @importFrom rtracklayer import.gff
#' @importFrom GenomicFeatures exonicParts
#' @importFrom GenomicRanges strand
#' @importFrom IRanges findOverlaps
#' @importFrom S4Vectors subjectHits queryHits mcols
#' @export
#' @title Preparing the genome annotation object
#' @description Flatten exon appearing multiple times among different transcripts in GTF file
#' @param gtffile GTF file.
#' @param singleGens Whether to allocate the exon overlapping with two genes to a single gene. Default is TRUE.
#' @param transposon A GRanges object with transposon data
#' @param minoverlap Minimum overlap for \code{\link[IRanges]{findOverlaps}}. Default is 10.
#' @param cores Number of cores used for parallel processing. Default is 1.
#' @importFrom BiocParallel bplapply MulticoreParam
#' @importFrom rtracklayer import.gff
#' @importFrom GenomicFeatures exonicParts 
#' @importFrom GenomicRanges strand
#' @importFrom IRanges findOverlaps
#' @importFrom S4Vectors subjectHits queryHits mcols
#' @export
prepareAnno <- function(gtffile, singleGens = TRUE, transposon = NULL, minoverlap = 10,  cores = 4) {
  gtfGr <- rtracklayer::import.gff(con = gtffile)
  message("Remove transcripts missing strand information.")
  gtfGr <- gtfGr[!GenomicRanges::strand(gtfGr) == "*"]
  txdb <- suppressWarnings({
    if (requireNamespace("txdbmaker", quietly = TRUE)) {
      txdbmaker::makeTxDbFromGRanges(gr = gtfGr)
    } else {
      GenomicFeatures::makeTxDbFromGRanges(gr = gtfGr)
    }
  })
  exonicParts <- GenomicFeatures::exonicParts(txdb = txdb, 
                                              linked.to.single.gene.only = singleGens)
  exonrank <- split(x = exonicParts$exonic_part, 
                    f = exonicParts$gene_id, drop = TRUE)
  gestrand <- split(x = GenomicRanges::strand(exonicParts), 
                    f = exonicParts$gene_id, drop = TRUE)
  
  message("Using ", cores, " cores for exon rank ordering.")
  exonicpart <- BiocParallel::bplapply(names(exonrank), BPPARAM = BiocParallel::MulticoreParam(cores), FUN = function(x) {
    if (unique(as.character(gestrand[[x]])) == "-") {
      order(as.integer(exonrank[[x]]), decreasing = TRUE)
    } else {
      order(as.integer(exonrank[[x]]))
    }
  })
  
  names(exonicpart) <- names(exonrank)
  exonicpart <- exonicpart[unique(exonicParts$gene_id)]
  exonicParts$exonic_part <- unlist(exonicpart)
  
  if (!is.null(transposon)) {
    if (!c("names") %in% colnames(S4Vectors::mcols(transposon)) || !is(transposon, "GRanges")) {
      stop("Transposone must be a Granges object that includes a column named 'names'.")
    }
    target_style <- suppressWarnings(GenomeInfoDb::seqlevelsStyle(exonicParts)[1])
    is_ncbi_format <- TRUE
    if (!is.na(target_style) && target_style == "UCSC") {
      is_ncbi_format <- FALSE
    }
    transposon <- NCBI_check(transposon, replace_name = FALSE, ncbi_style = is_ncbi_format)
    overlaps <- suppressWarnings(
      IRanges::findOverlaps(
        query = exonicParts,
        subject = transposon,
        minoverlap = minoverlap
      )
    )
    repeats <- split(x = transposon$names[S4Vectors::subjectHits(overlaps)], 
                     f = S4Vectors::queryHits(overlaps))
    repeats <- lapply(X = repeats, FUN = function(x) paste(x, collapse = ","))
    exonicParts$transposon <- "none"
    exonicParts$transposon[as.numeric(names(repeats))] <- unlist(repeats)
  }
  return(exonicParts)
}

#' @title Consolidation of information on transcript assembly of multiple samples
#' @description Transcript-quantification is prerequisite for many downstream investigations.
#' Several metrics have been proposed for measuring abundance in transcript level based on RNA-seq data.
#' @param reference Compared with a reference annotation file
#' @param bamFiles Character vector. BAM files (sorted by coordinate).
#' @param gtfFiles Character vector. Output GTF files (will be overwritten after re-quantification).
#' @param params Other parameters for StringTie
#' @param longRead Logical scalar or vector: TRUE for ONT/PacBio
#' @param cores Number of cores to use in parallel (default: 1)
#' @export
stringtieCombine <- function(reference = NULL, bamFiles = NULL, gtfFiles = NULL,
                             params = "", longRead = FALSE, cores = 1) {
  if (is.null(reference)) stop("Please provide the reference annotation file.")
  if (is.null(bamFiles) || is.null(gtfFiles)) stop("Please provide both `bamFiles` and `gtfFiles`.")
  if (length(bamFiles) != length(gtfFiles)) stop("`bamFiles` and `gtfFiles` must have the same length.")
  
  ## step 1: Re-quantify with -e
  rq_params <- paste("-e", params)
  message("Re-quantifying transcript abundance using ", cores, " core(s)...")
  
  parallel::mclapply(seq_along(bamFiles), function(i) {
    Teddy::stringtieAssembly(
      bam       = bamFiles[i],
      reference = reference,
      outfile   = gtfFiles[i],
      params    = rq_params,
      longRead  = longRead
    )
  }, mc.cores = cores)
  
  ## step 2: Preprocess gtf
  gtfGR <- rtracklayer::import.gff(reference)
  index <- which(gtfGR$type == "transcript")
  gtfGR$gene_name <- rep(
    gtfGR$gene_name[index],
    c(index[2:length(index)], length(gtfGR) + 1) - index
  )
  gtfGR$gene_name <- ifelse(is.na(gtfGR$gene_name), gtfGR$gene_id, gtfGR$gene_name)
  transcriptGR <- gtfGR[index]
  
  ## step 3: Extract quantification results
  SElist <- lapply(
    X = gtfFiles,
    FUN = .ExtractTranscript,
    transcriptGR = transcriptGR
  )
  
  ## step 4: Create SummarizedExperiment object
  SE <- do.call(cbind, SElist)
  S4Vectors::metadata(SE) <- list(gtf = .cleanGRanges(gtfGR))
  
  return(SE)
}

#' @title Counting reads on exon bins
#' @description Count reads overlapping exon bins defined in the flattened GTF/GFF object.
#' @param annotation A GRanges object, typically from prepareAnno().
#' @param bamfile Character vector of BAM file(s).
#' @param isPairedEnd Logical scalar or vector, whether the library is paired-end.
#' @param strandSpecific Integer: 0 (unstranded), 1 (forward), or 2 (reverse).
#' @param allowMultiOverlap Logical, whether to allow reads to overlap multiple features.
#' @param isLongRead Logical, whether this is long-read data (e.g. ONT, PacBio).
#' @param nthreads Number of BAM files processed in parallel.
#' @param ... Additional arguments passed to Rsubread::featureCounts().
#'
#' @return A RangedSummarizedExperiment object containing a counts assay.
#'
#' @importFrom SummarizedExperiment SummarizedExperiment
#' @importFrom S4Vectors DataFrame metadata
#' @importFrom Rsubread featureCounts
#' @importFrom parallel mclapply
#' @export
countAnno <- function(annotation, bamfile,
                      isPairedEnd = TRUE,
                      strandSpecific = 0,
                      allowMultiOverlap = TRUE,
                      isLongRead = FALSE,
                      nthreads = 1,
                      ...) {
  
  stopifnot(inherits(annotation, "GRanges"))
  stopifnot(is.character(bamfile))
  stopifnot(length(bamfile) >= 1)
  stopifnot(all(file.exists(bamfile)))
  stopifnot(length(nthreads) == 1, is.numeric(nthreads), nthreads >= 1)
  
  extra_args <- list(...)
  
  if ("nthreads" %in% names(extra_args)) {
    stop("Please specify 'nthreads' using the countAnno() argument, not through '...'.")
  }
  
  if ("isLongRead" %in% names(extra_args)) {
    stop("Please specify 'isLongRead' using the countAnno() argument, not through '...'.")
  }
  
  if (isLongRead && "maxMOp" %in% names(extra_args)) {
    extra_args$maxMOp <- NULL
    warning(
      "Long-read mode detected: ignoring 'maxMOp'. ",
      "Only 'isLongRead = TRUE' is passed to featureCounts()."
    )
  }
  
  annframe <- as.data.frame(annotation)
  names(annframe)[names(annframe) == "seqnames"] <- "Chr"
  annframe$GeneID <- paste(annotation$gene_id, annotation$exonic_part, sep = ":")
  
  if (length(isPairedEnd) == 1) {
    isPairedEnd <- rep(isPairedEnd, length(bamfile))
  }
  stopifnot(length(isPairedEnd) == length(bamfile))
  
  run_one_bam <- function(i) {
    one_bam <- bamfile[i]
    
    fc_args <- c(
      list(
        files = one_bam,
        annot.ext = annframe,
        isGTFAnnotationFile = FALSE,
        useMetaFeatures = FALSE,
        isPairedEnd = isPairedEnd[i],
        strandSpecific = strandSpecific,
        allowMultiOverlap = allowMultiOverlap,
        nthreads = 1L
      ),
      extra_args
    )
    
    if (isLongRead) {
      fc_args$isLongRead <- TRUE
    }
    
    fc <- do.call(Rsubread::featureCounts, fc_args)
    
    counts <- as.matrix(fc$counts)
    colnames(counts) <- basename(one_bam)
    
    list(
      counts = counts,
      stat = fc$stat
    )
  }
  
  fc_list <- parallel::mclapply(
    seq_along(bamfile),
    run_one_bam,
    mc.cores = min(as.integer(nthreads), length(bamfile))
  )
  
  count_mat <- do.call(
    cbind,
    lapply(fc_list, `[[`, "counts")
  )
  
  col_data <- S4Vectors::DataFrame(
    bamfile = bamfile,
    sample = basename(bamfile),
    row.names = basename(bamfile)
  )
  
  se <- SummarizedExperiment::SummarizedExperiment(
    assays = list(counts = count_mat),
    rowRanges = annotation,
    colData = col_data
  )
  
  S4Vectors::metadata(se)$featureCounts_stat <- lapply(fc_list, `[[`, "stat")
  names(S4Vectors::metadata(se)$featureCounts_stat) <- basename(bamfile)
  
  S4Vectors::metadata(se)$featureCounts_parameters <- list(
    isPairedEnd = isPairedEnd,
    strandSpecific = strandSpecific,
    allowMultiOverlap = allowMultiOverlap,
    isLongRead = isLongRead,
    featureCounts_nthreads_per_bam = 1L,
    sample_parallel_nthreads = min(as.integer(nthreads), length(bamfile))
  )
  
  se
}


#' @title Testing for differential TE-chimeric exon usage
#' @description Detect to what extent TE-chimeric exon affect the expression of the corresponding transcript
#' @param SEobject An object of RangedSummarizedExperiment class, out from \bold{countAnno}.
#' @param condition Vector, indicating the experimental condition of the samples.
#' @param annotation The genome annotation object, out from \bold{prepareAnno}.
#' @param maxit Control parameter: maximum number of iterations to allow for convergence when calculating dispersion.
#' @param niter Number of times to iterate between estimation of means and estimation of dispersion.
#' @param quiet Whether to suppress messages at each step.
#' @param warning Whether to print warnings at each step.
#' @param filterAllZero Logical, whether to remove all-zero rows before fitting the DESeq2 model.
#'
#' @import SummarizedExperiment
#' @importFrom DESeq2 DESeqDataSet estimateSizeFactorsForMatrix estimateDispersionsGeneEst estimateDispersionsFit estimateDispersionsPriorVar estimateDispersionsMAP nbinomLRT
#' @importClassesFrom SummarizedExperiment RangedSummarizedExperiment
#' @importFrom MatrixGenerics rowVars
#'
#' @export

ChimericDrivenTest <- function(SEobject,
                               condition = NULL,
                               annotation = NULL,
                               maxit = 100,
                               niter = 10,
                               quiet = FALSE,
                               warning = FALSE,
                               filterAllZero = FALSE) {
  old_warn <- getOption("warn")

  if (!warning) {
    options(warn = -1)
    on.exit(options(warn = old_warn), add = TRUE)
  }

  .msg <- function(...) {
    if (!quiet) {
      message("[", Sys.time(), "] ", ...)
    }
  }

  if (is.null(condition)) {
    stop("Please set the condition for the SummarizedExperiment object.")
  }

  if (is.null(SEobject@assays@data[["counts"]])) {
    stop("The count in the SummarizedExperiment object is needed.")
  }

  if (is.null(annotation)) {
    annotation <- rowRanges(SEobject)
  }

  design <- formula(x = "~ sample + chimeric + condition:chimeric")
  reducedModel <- formula(x = "~ sample + chimeric")

  colData(SEobject)$condition <- condition
  mcols(SEobject)$chimeric <- annotation$transposon

  meta <- as.data.frame(mcols(SEobject))
  sampleInfo <- colData(SEobject)

  featureID <- sprintf("E%3.3d", meta$exonic_part)
  groupID <- as.character(meta$gene_id)
  count <- as.matrix(SEobject@assays@data[["counts"]])

  if (length(groupID) != nrow(count)) {
    stop(
      "The length of 'groupID' must be the same as the number of rows in count matrix!",
      call. = FALSE
    )
  }

  if (length(featureID) != nrow(count)) {
    stop(
      "The length of 'featureID' parameter must be the same as the number of rows of countData!",
      call. = FALSE
    )
  }

  modelInfo <- cbind.data.frame(sample = rownames(sampleInfo), sampleInfo)

  modelInfo <- rbind.data.frame(
    cbind(modelInfo, chimeric = "chimeric"),
    cbind(modelInfo, chimeric = "others")
  )

  rownames(modelInfo) <- NULL

  vars <- all.vars(design)

  if (any(!vars %in% colnames(modelInfo))) {
    stop("The variable 'sample' in the design formula is not in the 'modelInfo'!")
  }

  .msg("Selecting genes with TE-chimeric exons")

  gene_exons <- split(seq_len(nrow(count)), as.character(groupID))

  identify_chimeric <- unlist(lapply(gene_exons, function(i) {
    any(meta$chimeric[i] != "none")
  }))

  chiobject <- SEobject[unlist(gene_exons[identify_chimeric]), ]

  chi_meta <- as.data.frame(mcols(chiobject))
  chi_featureID <- sprintf("E%3.3d", chi_meta$exonic_part)
  chi_groupID <- as.character(chi_meta$gene_id)
  chi_TEclass <- as.character(chi_meta$chimeric)
  chi_count <- as.matrix(chiobject@assays@data[["counts"]])

  rownames(chi_count) <- paste(chi_groupID, chi_featureID, sep = ":")

  chi_gene_exons <- split(seq_len(nrow(chi_count)), as.character(chi_groupID))

  .msg("Building chimeric-vs-others count matrix")

  others <- lapply(chi_gene_exons, function(i) {
    transposon <- chi_meta$chimeric[i]

    chi_idx <- which(transposon != "none")
    other_idx <- which(transposon == "none")
    subSE <- chi_count[i, , drop = FALSE]

    sumothers <- t(vapply(
      seq_along(chi_idx),
      function(r) {
        colSums(subSE[other_idx, , drop = FALSE])
      },
      numeric(ncol(subSE))
    ))

    rownames(sumothers) <- rownames(subSE)[chi_idx]

    sumothers
  })

  others <- do.call(rbind, others)

  chi_exon_ids <- chi_meta$chimeric != "none"
  chimeric <- chi_count[chi_exon_ids, , drop = FALSE]

  finalcount <- cbind(chimeric, others)

  chi_se <- SummarizedExperiment(finalcount, colData = modelInfo)

  mcols(chi_se)$featureID <- chi_featureID[chi_exon_ids]
  mcols(chi_se)$groupID <- chi_groupID[chi_exon_ids]
  mcols(chi_se)$TEclass <- chi_TEclass[chi_exon_ids]
  mcols(chi_se)$exonBaseMean <- rowMeans(finalcount)
  mcols(chi_se)$exonBaseVar <- rowVars(finalcount)

  .msg("Estimating size factors")

  normFactors <- estimateSizeFactorsForMatrix(count, median)
  chi_sizeFactors <- rep(normFactors, 2)

  modelInfo$sizefactor <- chi_sizeFactors

  normalizeSEcount <- function(object, sizefactors) {
    t(t(assay(object)) / sizefactors)
  }

  allZero <- unname(
    rowSums(finalcount) == 0 |
      rowSums(
        normalizeSEcount(chi_se, chi_sizeFactors)[, modelInfo$chimeric == "others"]
      ) == 0
  )

  mcols(chi_se)$allZero <- allZero

  if (filterAllZero) {
    .msg("Filtering all-zero rows: ", sum(allZero), " / ", length(allZero))
    chi_se <- chi_se[!allZero, ]
  } else {
    .msg(
      "Keeping all rows; all-zero rows are marked only: ",
      sum(allZero), " / ", length(allZero)
    )
  }

  .msg("Building DESeqDataSet")

  chi_dds <- DESeqDataSet(chi_se, design, ignoreRank = TRUE)

  colData(chi_dds)$sizeFactor <- chi_sizeFactors

  .msg("Building model matrices")

  fullModelM <- rmDepCols(model.matrix(design, modelInfo))
  reducedModelM <- rmDepCols(model.matrix(reducedModel, modelInfo))

  .msg("Estimating gene-wise dispersions")

  chi_dds <- DESeq2::estimateDispersionsGeneEst(
    chi_dds,
    maxit = maxit,
    quiet = quiet,
    modelMatrix = fullModelM,
    niter = niter
  )

  .msg("Fitting dispersion trend")

  chi_dds <- estimateDispersionsFit(
    chi_dds,
    fitType = "parametric",
    minDisp = 1e-08,
    quiet = quiet
  )

  .msg("Estimating dispersion prior variance")

  dispersion_priorvar <- estimateDispersionsPriorVar(
    chi_dds,
    minDisp = 1e-08,
    modelMatrix = fullModelM
  )

  .msg("Estimating MAP dispersions")

  chi_dds <- estimateDispersionsMAP(
    chi_dds,
    dispPriorVar = dispersion_priorvar,
    modelMatrix = fullModelM
  )

  .msg("Running nbinomLRT")

  chi_test <- nbinomLRT(
    chi_dds,
    reduced = reducedModelM,
    full = fullModelM
  )

  .msg("Done")

  chi_test
}

#' @title Extract results from the differential TE-bin usage test
#' @param object An object from \bold{ChimericDrivenTest}.
#' @param filter Logical. If \code{TRUE} (default), filter out features with \code{NA} adjusted p-values
#' and features flagged as structural zeros (\code{allZero}).
#' @export
extractTest <- function(object, filter = TRUE) {
  LRTout <- DESeq2::results(object)
  
  chimericCounts_N <- DESeq2::counts(object, normalized = TRUE)[, colData(object)$chimeric == "chimeric"]
  LRTout$exonExpr <- rowMeans(chimericCounts_N)
  
  LRTout$featureID  <- S4Vectors::mcols(object)$featureID
  LRTout$groupID    <- S4Vectors::mcols(object)$groupID
  LRTout$TEclass    <- S4Vectors::mcols(object)$TEclass
  LRTout$dispersion <- S4Vectors::mcols(object)$dispersion
  LRTout$allZero    <- S4Vectors::mcols(object)$allZero
  
  # Ensure BH-adjusted p-values are present (DESeq2 typically provides this already)
  LRTout$padj <- p.adjust(LRTout$pvalue, method = "BH")
  
  LRTout <- LRTout[, c("groupID", "featureID", "exonExpr", "TEclass",
                       "dispersion", "stat", "pvalue", "padj", "allZero")]
  
  if (isTRUE(filter)) {
    LRTout <- LRTout[!is.na(LRTout$padj) & !LRTout$allZero, ]
  }
  
  S4Vectors::mcols(LRTout)[1:5, 1] <- "input"
  S4Vectors::mcols(LRTout)[1:5, 2] <- c("GeneID", "BinID", "Mean normalized count of the tested TE-bin feature",
                                        "TEclass", "Dispersion estimate")
  LRTout
}

#' @title Calculating the fold change
#' @description TE-chimeric exon usage fold changes are calculated based on the coefficients of the GLM fit
#' @param object An object of test
#' @param genes Specify the genes for the calculation of foldchanges
#' @param corssVar Default as "condition"
#' @importFrom BiocParallel bplapply
#' @import statmod methods 
#' @importFrom stats as.formula
#' @export
calculateFoldchange <- function(object,
                                genes,
                                crossVar = "condition"){
  frm <- stats::as.formula(paste("count ~", crossVar, "*Chimeric"))
  findex <- !is.na(DESeq2::results(object)$padj) & !mcols(object)$allZero
  groups <- mcols(object)$groupID
  features <- mcols(object)$featureID
  modelInfo <- colData(object)
  N_samples <- nrow(modelInfo) / 2
  disp <- DESeq2::dispersions(object)
  disp[is.na(disp)] <- 1e-6
  chimericCounts <- counts(object)[,colData(object)$chimeric == "chimeric"]
  otherCounts <- counts(object)[,colData(object)$chimeric == "others"]
  samples <- unique(colData(object)$sample)
  mfSmall <- as.data.frame(colData(object))
  genes <- intersect(
    genes,
    unique(groups[findex])
  )
  if (length(genes) > 0L) {
    alleffects <- BiocParallel::bplapply( genes,
                            getEffectsForGene,
                            groups = groups, 
                            otherCounts = otherCounts,
                            chimericCounts = chimericCounts,
                            disp = disp,
                            mf = mfSmall, 
                            frm = frm,
                            findex = findex,
                            N_samples = N_samples,
                            samples = samples,
                            features = features,
                            object = object)
    names(alleffects) <- genes
  }
  return(alleffects)
}





#' Process GTF and SummarizedExperiment for TE overlap analysis
#'
#' This function processes a GTF file or a SummarizedExperiment object to identify overlaps with transposable elements (TE).
#' It can handle both external (local) GTF files and in-memory SummarizedExperiment objects. 
#' The function extracts exon and transcript information, finds overlaps with TE annotations, and filters out transcripts with zero expression.
#'
#' @param te GRanges object. Transposable element annotations, required for overlap analysis.
#' The `te` object must contain at least three metadata columns: `names`, `family`, and `class`. 
#' @param gtfPath Character. Path to the GTF file (optional, required if combineSE is NULL).
#' @param combineSE SummarizedExperiment. Pre-processed RNA-seq quantification object (optional, required if gtfPath is NULL).
#' @param minoverlap Integer. Minimum required overlap (in base pairs) between GTF exons and TE annotations. Default is 0.
#' @param threads Integer. Number of threads to use for parallel processing. Default is 9.
#' 
#' @return A GRanges object with transcripts overlapping TEs, annotated with TE information.
#' 
#' @import BiocParallel
#' @import GenomicRanges
#' @importFrom rtracklayer import
#' @importFrom S4Vectors queryHits subjectHits
#' @importFrom GenomeInfoDb genome seqlevels
#' 
#' @export
processGTF <- function(te, gtfPath = NULL, combineSE = NULL,
                       minoverlap = 0, threads = 9) {
  
  if (!is.null(combineSE)) {
    combineSE <- .checkCombineSE(combineSE)
    GTF <- S4Vectors::metadata(combineSE)$gtf
  } else if (!is.null(gtfPath)) {
    GTF <- .cleanGRanges(rtracklayer::import(gtfPath))
  } else {
    stop("Please provide either a gtfPath or a combineSE object.")
  }
  
  if (!inherits(GTF, "GRanges")) {
    stop("GTF must be a GRanges object.")
  }
  
  gtf_mc <- S4Vectors::mcols(GTF)
  required_gtf_cols <- c("type", "transcript_id", "exon_number")
  miss <- setdiff(required_gtf_cols, colnames(gtf_mc))
  if (length(miss) > 0) {
    stop("GTF is missing required column(s): ", paste(miss, collapse = ", "))
  }
  
  required_te_cols <- c("names", "family", "class")
  miss_te <- setdiff(required_te_cols, colnames(S4Vectors::mcols(te)))
  if (length(miss_te) > 0) {
    stop("te is missing required column(s): ", paste(miss_te, collapse = ", "))
  }
  
  ## fill exon-level gene_name from transcript rows if needed
  if ("gene_name" %in% colnames(gtf_mc)) {
    tx_gene <- as.character(gtf_mc$gene_name[as.character(gtf_mc$type) == "transcript"])
    names(tx_gene) <- as.character(gtf_mc$transcript_id[as.character(gtf_mc$type) == "transcript"])
  } else {
    tx_gene <- character()
  }
  
  ## keep exon rows
  GTF <- GTF[as.character(gtf_mc$type) == "exon"]
  GTF <- GTF[GenomicRanges::strand(GTF) != "*"]
  
  mc <- S4Vectors::mcols(GTF)
  
  if (!"gene_name" %in% colnames(mc)) {
    mc$gene_name <- NA_character_
  }
  
  if (length(tx_gene) > 0) {
    exon_tx <- as.character(mc$transcript_id)
    fill_gene <- tx_gene[exon_tx]
    need_fill <- is.na(mc$gene_name) | mc$gene_name == ""
    mc$gene_name[need_fill] <- fill_gene[need_fill]
  }
  
  S4Vectors::mcols(GTF) <- mc
  
  mc <- S4Vectors::mcols(GTF)
  tx_ids <- unique(as.character(mc$transcript_id))
  
  t_exonRank <- split(
    x = as.character(mc$exon_number),
    f = as.character(mc$transcript_id)
  )
  t_exonRank <- t_exonRank[tx_ids]
  
  t_gestrand <- split(
    x = as.character(GenomicRanges::strand(GTF)),
    f = as.character(mc$transcript_id),
    drop = TRUE
  )
  t_gestrand <- t_gestrand[tx_ids]
  
  bp_param <- BiocParallel::MulticoreParam(workers = threads)
  
  exoninTx <- BiocParallel::bplapply(names(t_exonRank), function(x) {
    if (unique(as.character(t_gestrand[[x]])) == "-") {
      order(as.integer(t_exonRank[[x]]), decreasing = TRUE)
    } else {
      order(as.integer(t_exonRank[[x]]))
    }
  }, BPPARAM = bp_param)
  
  names(exoninTx) <- tx_ids
  S4Vectors::mcols(GTF)$tx_exon_rank <- unlist(
    exoninTx,
    recursive = FALSE,
    use.names = TRUE
  )
  
  if (length(intersect(GenomeInfoDb::seqlevels(GTF), GenomeInfoDb::seqlevels(te))) == 0) {
    stop(
      "No common seqlevels between GTF and TE annotations. ",
      "Please check chromosome naming style, e.g. 'chr1' versus '1'."
    )
  }
  
  
  overlaps <- GenomicRanges::findOverlaps(GTF, te, minoverlap = minoverlap)
  
  if (length(overlaps) == 0) {
    warning("No overlaps found between GTF exons and TE annotations.")
    return(GTF[0])
  }
  
  class <- split(
    x = as.character(S4Vectors::mcols(te)$class[S4Vectors::subjectHits(overlaps)]),
    f = S4Vectors::queryHits(overlaps)
  )
  class <- lapply(class, function(x) paste(unique(x), collapse = ","))
  
  repeats <- split(
    x = as.character(S4Vectors::mcols(te)$names[S4Vectors::subjectHits(overlaps)]),
    f = S4Vectors::queryHits(overlaps)
  )
  repeats <- lapply(repeats, function(x) paste(unique(x), collapse = ","))
  
  family <- split(
    x = as.character(S4Vectors::mcols(te)$family[S4Vectors::subjectHits(overlaps)]),
    f = S4Vectors::queryHits(overlaps)
  )
  family <- lapply(family, function(x) paste(unique(x), collapse = ","))
  
  S4Vectors::mcols(GTF)$TE_name <- "none"
  S4Vectors::mcols(GTF)$TE_name[as.integer(names(repeats))] <- unlist(repeats)
  
  S4Vectors::mcols(GTF)$TE_class <- "none"
  S4Vectors::mcols(GTF)$TE_class[as.integer(names(class))] <- unlist(class)
  
  S4Vectors::mcols(GTF)$TE_family <- "none"
  S4Vectors::mcols(GTF)$TE_family[as.integer(names(family))] <- unlist(family)
  
  CHI_GTF <- GTF[S4Vectors::mcols(GTF)$TE_name != "none"]
  
  ## remove metadata columns that are entirely NA
  chi_mc <- S4Vectors::mcols(CHI_GTF)
  keep_cols <- vapply(seq_along(chi_mc), function(i) {
    !all(is.na(chi_mc[[i]]))
  }, logical(1))
  
  S4Vectors::mcols(CHI_GTF) <- chi_mc[, keep_cols, drop = FALSE]
  
  CHI_GTF
}

#' @title Build an isoform support matrix across multiple GTF files
#' @description Compare multiple query GTF files against a reference transcriptome and return a presence/absence matrix based on gffcompare tracking files.
#' @param reference Character. Path to the reference GTF.
#' @param gtffiles Character vector. Paths to query GTF files.
#' @param conditions Character vector. Sample, platform, or depth names corresponding to `gtffiles`.
#' @param out_dir Character. Output directory for gffcompare results.
#' @param out_prefix Character. Prefix for output files.
#' @param params Additional parameters passed to gffcompare.
#' @param FPKM Optional numeric matrix. Rows correspond to isoforms and columns correspond to `conditions`.
#' @param threshold Numeric. FPKM cutoff used when refining presence.
#' @param cores Integer. Number of cores for parallel execution.
#' @param fill_missing_annot Logical. Whether to fill missing annotation using `lookup_annot_tx()`. Default is FALSE.
#' @return A tibble with one row per reference transcript and one logical column per condition.
#' @export
buildIsoformSupport <- function(reference,
                                gtffiles,
                                conditions,
                                out_dir = ".",
                                out_prefix = "cmp",
                                params = "",
                                FPKM = NULL,
                                threshold = 0.1,
                                cores = 4,
                                fill_missing_annot = FALSE) {
  stopifnot(length(gtffiles) == length(conditions))
  
  if (!file.exists(reference)) {
    stop("Reference GTF not found: ", reference)
  }
  
  if (!all(file.exists(gtffiles))) {
    stop("Some query GTF files do not exist.")
  }
  
  dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
  
  tracking_paths <- parallel::mclapply(seq_along(gtffiles), function(i) {
    outfile <- file.path(out_dir, paste0(out_prefix, "_", conditions[i], ".gtf"))
    
    gffcompareAnno(
      reference = reference,
      gtffile = gtffiles[i],
      outfile = outfile,
      params = params,
      overwrite = TRUE
    )
    
    tracking <- sub("\\.gtf$", ".tracking", outfile)
    
    if (!file.exists(tracking)) {
      stop("Tracking file not found: ", tracking)
    }
    
    tracking
  }, mc.cores = cores) |> unlist()
  
  buildIsoformPresence(
    trackingFiles = tracking_paths,
    conditions = conditions,
    reference = reference,
    fpkm_mat = FPKM,
    threshold = threshold,
    cores = cores,
    fill_missing_annot = fill_missing_annot
  )
}

