
#' Extract GTF Based on Type and FPKM Filter
#'
#' This function filters and extracts GTF information from a `SummarizedExperiment` object 
#' based on the specified element type (exon, transcript, or both) and an FPKM threshold. 
#' It is designed to work with `SummarizedExperiment` objects containing GTF metadata and FPKM assay data.
#'
#' @param combineSE Optional. A `SummarizedExperiment` object generated by `stringtieCombine()`,
#' containing GTF metadata in `metadata(combineSE)$gtf` and an `FPKM` assay.
#' @param gtfFile Optional. Path to an annotated GTF file. If provided without `combineSE`,
#' the function imports the GTF directly and filters only by `type`.
#' @param filter A numeric value specifying the minimum FPKM threshold for transcripts to be included in the output. 
#' Default is 1.
#' @param type A character string specifying the type of genetic elements to extract. 
#' Valid options are "exon", "transcript", or "both". Default is "exon".
#'
#' @return A filtered subset of the GTF metadata, 
#' including only the specified types of genetic elements that meet the FPKM threshold.
#'
#' @export
#'
extractGTF <- function(combineSE = NULL,
                       gtfFile = NULL,
                       filter = 1,
                       type = c("exon", "transcript", "both")) {
  
  type <- match.arg(type)
  
  if (!is.null(combineSE)) {
    if (!inherits(combineSE, "SummarizedExperiment")) {
      stop("combineSE must be a SummarizedExperiment object")
    }
    
    if (!"FPKM" %in% names(SummarizedExperiment::assays(combineSE))) {
      stop("combineSE must contain an assay named 'FPKM'.")
    }
    
    if (is.null(S4Vectors::metadata(combineSE)$gtf)) {
      stop("combineSE must contain GTF metadata in metadata(combineSE)$gtf.")
    }
    
    Transcript_FPKM_index <- rowSums(SummarizedExperiment::assay(combineSE, "FPKM") > filter) >= 1
    sub_combineSE <- combineSE[Transcript_FPKM_index, ]
    
    GTF <- S4Vectors::metadata(sub_combineSE)$gtf
    
  } else if (!is.null(gtfFile)) {
    GTF <- rtracklayer::import(gtfFile)
  } else {
    stop("Please provide either combineSE or gtfFile.")
  }

  if (type == "exon") {
    GTF <- GTF[GTF$type == "exon", ]
  } else if (type == "transcript") {
    GTF <- GTF[GTF$type == "transcript", ]
  } else if (type == "both") {
    GTF <- GTF[GTF$type %in% c("exon", "transcript"), ]
  }
  
  mcols_GTF <- S4Vectors::mcols(GTF)
  
  if (ncol(mcols_GTF) > 0) {
    keep_cols <- !vapply(
      as.data.frame(mcols_GTF),
      function(x) all(is.na(x)),
      logical(1)
    )
    S4Vectors::mcols(GTF) <- mcols_GTF[, keep_cols, drop = FALSE]
  }
  
  return(GTF)
}


#' Pick TE-chimeric transcript(s) for a gene
#'
#' Selects TE-chimeric transcript(s) associated with a given gene. Input can be
#' either a precomputed `chi_GTF` from `processGTF()` or a `combineSE` object
#' together with TE annotation. If expression data are provided through `expr`
#' or `combineSE`, matched transcripts are ranked by mean expression.
#'
#' @param gene Character. Gene name or gene ID to query.
#' @param chi_GTF Optional `GRanges` object generated by `processGTF()`.
#' @param combineSE Optional `SummarizedExperiment` generated by `stringtieCombine()`.
#' @param te Optional `GRanges` TE annotation. Required when `combineSE` is used
#' and `chi_GTF` is not provided.
#' @param gene_col Character. Column used for gene matching. Default is `"gene_name"`.
#' @param assay_name Character. Assay used for expression ranking when `combineSE`
#' is provided. Default is `"FPKM"`.
#' @param expr Optional expression matrix used for ranking chimeric transcripts.
#' Rows should be transcript IDs and columns should be samples.
#' @param samples Optional character or integer vector. Samples/columns used for
#' expression ranking. If `NULL`, all columns are used.
#' @param return_all Logical. Whether to return all matched transcript IDs.
#' @param minoverlap Integer. Minimum overlap passed to `processGTF()`.
#' @param threads Integer. Number of threads passed to `processGTF()`.
#'
#' @return A character vector of transcript ID(s), or `NA_character_`.
#'
#' @export
pick_chimeric_tx <- function(gene,
                             chi_GTF = NULL,
                             combineSE = NULL,
                             te = NULL,
                             gene_col = "gene_name",
                             assay_name = "FPKM",
                             expr = NULL,
                             samples = NULL,
                             return_all = FALSE,
                             minoverlap = 5,
                             threads = 8) {
  if (is.null(chi_GTF) && is.null(combineSE)) {
    stop("Please provide either chi_GTF or combineSE.")
  }
  
  if (is.null(chi_GTF)) {
    if (is.null(te)) {
      stop("te must be provided when chi_GTF is NULL and combineSE is used.")
    }
    
    chi_GTF <- processGTF(
      te = te,
      combineSE = combineSE,
      minoverlap = minoverlap,
      threads = threads
    )
  }
  
  if (!inherits(chi_GTF, "GRanges")) {
    stop("chi_GTF must be a GRanges object generated by processGTF().")
  }
  
  mc <- S4Vectors::mcols(chi_GTF)
  
  if (!gene_col %in% colnames(mc)) {
    stop("gene_col was not found in chi_GTF.")
  }
  
  if (!"transcript_id" %in% colnames(mc)) {
    stop("chi_GTF must contain a transcript_id column.")
  }
  
  gene_vec <- as.character(mc[[gene_col]])
  keep <- !is.na(gene_vec) & gene_vec == gene
  tx <- unique(as.character(mc$transcript_id[keep]))
  tx <- tx[!is.na(tx) & tx != ""]
  
  if (length(tx) == 0) {
    return(NA_character_)
  }
  
  if (isTRUE(return_all)) {
    return(tx)
  }
  
  if (!is.null(combineSE)) {
    if (!inherits(combineSE, "SummarizedExperiment")) {
      stop("combineSE must be a SummarizedExperiment object.")
    }
    if (!assay_name %in% SummarizedExperiment::assayNames(combineSE)) {
      stop("assay_name was not found in combineSE assays.")
    }
    expr <- SummarizedExperiment::assay(combineSE, assay_name)
  }
  if (!is.null(expr)) {
    if (is.null(rownames(expr))) {
      stop("expr must have transcript IDs as rownames.")
    }
    if (!is.null(samples)) {
      if (is.character(samples)) {
        miss <- setdiff(samples, colnames(expr))
        if (length(miss) > 0) {
          stop("samples not found in expression columns: ",
               paste(miss, collapse = ", "))
        }
      }
      expr <- expr[, samples, drop = FALSE]
    }
    tx2 <- tx[tx %in% rownames(expr)]
    if (length(tx2) == 0) {
      warning("Matched chimeric transcript(s) were not found in expression rownames; returning the first matched transcript.")
      return(tx[1])
    }
    mat <- expr[tx2, , drop = FALSE]
    return(tx2[which.max(rowMeans(mat, na.rm = TRUE))])
  }
  if (!is.null(samples)) {
    warning("No expression data provided; samples will be ignored and transcript selection will not be expression-based.")
  }
  tx[1]
}

#' Pick the most expressed reference transcript for a gene
#'
#' Selects the highest-expressed reference transcript for a given gene from a
#' `SummarizedExperiment` object generated by `stringtieCombine()`.
#'
#' @param combineSE A `SummarizedExperiment` object generated by `stringtieCombine()`.
#' @param gene Character. Gene name to query.
#' @param assay_name Character. Assay used for ranking. Default is `"FPKM"`.
#' @param samples Optional character or integer vector. Samples/columns used for
#' expression ranking. If `NULL`, all columns are used.
#' @param ref_tx_pattern Optional regular expression used to restrict reference
#' transcript IDs. Default is `"^ENS"`. Set to `NULL` to disable this filter.
#'
#' @return A character scalar transcript ID. Returns `NA_character_` if no match is found.
#'
#' @export
pick_canonical_tx <- function(combineSE,
                              gene,
                              assay_name = "FPKM",
                              samples = NULL,
                              ref_tx_pattern = "^ENS") {
  if (!inherits(combineSE, "SummarizedExperiment")) {
    stop("combineSE must be a SummarizedExperiment object.")
  }
  
  if (!assay_name %in% SummarizedExperiment::assayNames(combineSE)) {
    stop("assay_name was not found in combineSE assays.")
  }
  
  expr <- SummarizedExperiment::assay(combineSE, assay_name)
  
  if (!is.null(samples)) {
    if (is.character(samples)) {
      miss <- setdiff(samples, colnames(expr))
      if (length(miss) > 0) {
        stop("samples not found in assay columns: ", paste(miss, collapse = ", "))
      }
    }
    expr <- expr[, samples, drop = FALSE]
  }
  
  mc <- S4Vectors::mcols(SummarizedExperiment::rowRanges(combineSE))
  
  required_cols <- c("transcript_id", "gene_name")
  miss <- setdiff(required_cols, colnames(mc))
  if (length(miss) > 0) {
    stop("rowRanges(combineSE) is missing required column(s): ",
         paste(miss, collapse = ", "))
  }
  
  gene_vec <- as.character(mc$gene_name)
  tx_vec <- as.character(mc$transcript_id)
  
  keep <- !is.na(gene_vec) &
    gene_vec == gene &
    !is.na(tx_vec)
  
  if (!is.null(ref_tx_pattern)) {
    keep <- keep & grepl(ref_tx_pattern, tx_vec)
  }
  
  tx <- unique(tx_vec[keep])
  tx <- tx[!is.na(tx) & tx != ""]
  tx <- tx[tx %in% rownames(expr)]
  
  if (length(tx) == 0) {
    return(NA_character_)
  }
  
  mat <- expr[tx, , drop = FALSE]
  tx[which.max(rowMeans(mat, na.rm = TRUE))]
}


#' Standardize transposon annotations for TEDDY
#'
#' This helper prepares a transposon annotation object for TEDDY by converting
#' chromosome naming to NCBI or UCSC style and ensuring that a TE-name metadata column
#' named `names` is available. If `names` is absent, common TE-name columns such
#' as `name`, `repName`, `repname`, or `TE_name` are used to create it.
#'
#' @param transposon A \link[GenomicRanges:GRanges-class]{GRanges} object
#'   containing transposon annotations.
#' @param replace_name Logical. If `TRUE` and the object contains a `name`
#'   column but not a `names` column, the `name` column is renamed to `names`.
#'   If `FALSE`, a new `names` column is created while preserving the original
#'   `name` column. Default is `FALSE`.
#' @param ncbi_style Logical. If `TRUE` (default), chromosome names are converted
#'   to NCBI style (e.g., '1', '2'). If `FALSE`, they are converted to UCSC style 
#'   (e.g., 'chr1', 'chr2').
#'
#' @return A \link[GenomicRanges:GRanges-class]{GRanges} object with standardized
#'   chromosome names and a character metadata column named `names`.
#' @export
#'
NCBI_check <- function(transposon, replace_name = FALSE, ncbi_style = TRUE) {
  if (!inherits(transposon, "GRanges")) {
    stop("`transposon` must be a GRanges object.")
  }
  
  mcols_names <- colnames(S4Vectors::mcols(transposon))
  
  if (!"names" %in% mcols_names) {
    candidate_cols <- c("name", "repName", "repname", "TE_name")
    hit <- candidate_cols[candidate_cols %in% mcols_names][1]
    
    if (!is.na(hit)) {
      if (replace_name && hit == "name") {
        colnames(S4Vectors::mcols(transposon))[
          colnames(S4Vectors::mcols(transposon)) == "name"
        ] <- "names"
      } else {
        transposon$names <- as.character(S4Vectors::mcols(transposon)[[hit]])
      }
    } else {
      stop("Required TE name column missing. Please provide one of: `names`, `name`, `repName`, `repname`, or `TE_name`.")
    }
  } else {
    transposon$names <- as.character(transposon$names)
  }
  
  target_style <- ifelse(ncbi_style, "NCBI", "UCSC")
  suppressWarnings(GenomeInfoDb::seqlevelsStyle(transposon) <- target_style)
  
  return(transposon)
}


.Stringtiebin <- function(args = "") {
  if (is.null(args) || args == "") {
    stop("The StringTie executables require additional arguments.")
  }
  args <- gsub("^ *| *$", "", args)
  args <- unlist(strsplit(args, split = " "))
  bin <- file.path(system.file(package = "Teddy"), "stringtie")
  output <- system2(command = bin, args = args)
}


.Stringtiebin3 <- function(args = "") {
  if (is.null(args) || args == "") {
    stop("The StringTie executables require additional arguments.")
  }
  args <- gsub("^ *| *$", "", args)
  args <- unlist(strsplit(args, split = " "))
  bin <- file.path(system.file(package = "Teddy"), "stringtie3", "stringtie")
  output <- system2(command = bin, args = args)
  return(output)
}

.gffcompareBin <- function(args = "") {
  if (is.null(args) || args == "") {
    stop("Gffcompare requires additional arguments.")
  }
  args <- gsub("^ *| *$", "", args)
  args <- unlist(strsplit(args, split = " "))
  bin <- file.path(system.file(package = "Teddy"), "gffcompare")
  output <- system2(command = bin, args = args)
}



.parseDots <- function(...) {
  if (...length() == 0) return("")
  dots <- list(...)
  args <- lapply(names(dots), FUN = function(x) {
    paste(x, dots[x], sep = " ")
  })
  args <- paste0(unlist(args), collapse = " ")
  return(args)
}

.ExtractTranscript <- function(gtf, transcriptGR) {
  gtfs <- rtracklayer::import.gff(gtf)
  
  transcript <- gtfs[gtfs$type == "transcript"]
  exprts <- GenomicRanges::mcols(transcript)[, c("cov", "FPKM", "TPM")]
  exprts <- apply(X = exprts, MARGIN = 2, as.numeric)
  exprts <- as.data.frame(exprts, row.names = transcript$transcript_id)
  
  express <- matrix(0, nrow = length(transcriptGR), ncol = 3,
                    dimnames = list(transcriptGR$transcript_id,
                                    c("cov", "FPKM", "TPM")))
  express <- as.data.frame(express)
  
  express[rownames(exprts), ] <- exprts
  express <- express[transcriptGR$transcript_id, ]
  
  gtf <- basename(gtf)
  sample <- gsub(pattern = ".gtf$", replacement = "", x = gtf)
  coldata <- data.frame(row.names = sample, sample = sample)
  
  
  cov <- express[, 'cov', drop = FALSE]
  colnames(cov) <- sample
  FPKM = express[, 'FPKM', drop = FALSE]
  colnames(FPKM) <- sample
  TPM = express[, "TPM", drop = FALSE]
  colnames(TPM) <- sample
  
  SE <- SummarizedExperiment::SummarizedExperiment(
    S4Vectors::SimpleList(cov = cov, FPKM = FPKM,
                          TPM = TPM),
                          rowRanges = transcriptGR,
                          colData = coldata)
  return(SE)
}



UnfoldCoefs <- function(varlist, fit, mm, mf){
  coefLists <- lapply(seq(ncol(varlist)), function(index) {
    termName <- colnames(varlist)[index]
    varsInTerm <- stringr::str_split(termName, stringr::fixed(":"))[[1]]
    stopifnot(all(varlist[varsInTerm, index] == 1))
    stopifnot(sum(varlist[ , index]) == length(varsInTerm))
    coefNames <- colnames(mm)[index+1]
    varLevels <- lapply(varsInTerm, function(v) levels(factor(mf[[v]])))
    coefIndices <- array(0, dim = sapply(varLevels, length), dimnames = varLevels)
    lvlTbl <- stringr::str_match(coefNames, stringr::str_c( "^", stringr::str_c( varsInTerm, "([^:]*)", collapse=":" ), "$" ) )[ , -1, drop=FALSE]
    coefIndices[lvlTbl] <- coefficients(fit)[coefNames]
    coefIndices
  })
  names(coefLists) <- colnames(varlist)
  a <- array(c(`(Intercept)` = "(Intercept)"))
  coefLists <- c(list(a), coefLists)
  names(coefLists)[1] <- "intercept"
  coefLists[1] <- coefficients(fit)[1]
  return(coefLists)
}

rmDepCols <- function(m) {
  q <- qr(m)
  if (q$rank < ncol(m)) 
    m[, -q$pivot[(q$rank + 1):ncol(m)]]
  else m
}

getEffectsForGene <- function(gene,
                              groups,
                              findex,
                              frm,
                              mf,
                              disp,
                              otherCounts,
                              chimericCounts,
                              N_samples,
                              samples,
                              features,
                              object){
  idx <- groups %in% gene & findex
  sub_chimericCounts <- chimericCounts[idx, ,drop = FALSE]
  sub_otherCounts <- otherCounts[idx, ,drop = FALSE]
  sub_disp <- disp[idx]
  names(sub_disp) <- features[idx]
  N_exons <- sum(idx)
  newMf <- as.data.frame(rep(samples, each = N_exons))
  colnames(newMf) <- "sample"
  chi_sizeFactors <- mf$sizeFactor[colData(object)$chimeric == "chimeric"]
  chi_condition <- mf$condition[colData(object)$chimeric == "chimeric"]
  newMf$count <- as.vector(t(sub_chimericCounts[, samples]))
  newMf$dispersion <- rep(sub_disp, N_samples)
  newMf$sizeFactors <- rep(chi_sizeFactors, each = N_exons)
  newMf$Chimeric <- "chimeric"
  newMf$condition <- rep(chi_condition, each = N_exons)
  othersMf <- newMf
  othersMf$Chimeric <- "others"
  othersMf$count <- as.vector(t(sub_otherCounts[, samples]))
  Mf <- rbind(othersMf, newMf)[,c("sample", "condition", "Chimeric", "sizeFactors", "dispersion", "count")]
  Mf$Chimeric <- factor(Mf$Chimeric, levels = c("others", "chimeric"))
  mm <- model.matrix(frm, Mf)
  fit <- glmnb.fit(mm, Mf$count, dispersion = Mf$dispersion, offset = log(Mf$sizeFactors), tol=0.01)
  varlist <- attr(terms(frm), "factors")
  coef <- UnfoldCoefs(varlist = varlist, fit = fit, mm = mm, mf = Mf)
  return(coef)
}


lookup_annot_tx <- function(tcons, ref_gtf) {
  res <- suppressWarnings(
    system2(
      "grep",
      args = c("-m", "1", tcons, ref_gtf),
      stdout = TRUE,
      stderr = FALSE
    )
  )
  
  if (length(res) == 0) {
    return(NA_character_)
  }
  
  gene_id <- sub('.*gene_id "([^"]+)".*', "\\1", res[1])
  tx_id   <- sub('.*transcript_id "([^"]+)".*', "\\1", res[1])
  
  if (gene_id == res[1] || tx_id == res[1]) {
    return(NA_character_)
  }
  paste0(gene_id, "|", tx_id)
}


#' Clean sample names
#' Remove replicate suffixes from sample names.
#' @param names Character vector of sample names.
#' @return A character vector with replicate suffixes removed.
#' @export
clean_sampleNames <- function(names) {
  gsub("[-_\\.]?(rep|r)?[0-9]+$", "", names, ignore.case = TRUE)
}


buildIsoformPresence <- function(trackingFiles,
                                 conditions,
                                 reference = NULL,
                                 fpkm_mat = NULL,
                                 threshold = 0.1,
                                 cores = 8,
                                 fill_missing_annot = FALSE) {
  stopifnot(length(trackingFiles) == length(conditions))
  stopifnot(all(file.exists(trackingFiles)))
  
  read_one <- function(f) {
    trk <- readr::read_tsv(
      f,
      col_names = FALSE,
      comment = "#",
      show_col_types = FALSE
    )
    
    x3_clean <- ifelse(trk$X3 == "-" | is.na(trk$X3), NA, trk$X3)
    
    tibble::tibble(
      TCONS = trk$X1,
      annot_tx = x3_clean,
      support = trk$X4 == "="
    )
  }
  
  lst <- lapply(trackingFiles, read_one)
  
  all_TCONS <- Reduce(union, lapply(lst, function(x) x$TCONS)) |> sort()
  emp_anno <- rep(NA_character_, length(all_TCONS))
  names(emp_anno) <- all_TCONS
  
  lst_full <- lapply(lst, function(df) {
    dplyr::right_join(
      df,
      tibble::tibble(TCONS = all_TCONS),
      by = "TCONS"
    ) |>
      dplyr::mutate(
        support = ifelse(is.na(support), FALSE, support)
      )
  })
  
  invisible(lapply(lst_full, function(df) {
    good <- !is.na(df$annot_tx) & df$annot_tx != "-"
    fill_idx <- which(is.na(emp_anno) & good)
    
    if (length(fill_idx) > 0) {
      emp_anno[fill_idx] <<- df$annot_tx[fill_idx]
    }
  }))
  
  support_tbl <- Reduce(
    function(x, y) dplyr::full_join(x, y, by = "TCONS"),
    lst_full
  )
  
  missing_idx <- which(is.na(emp_anno))
  
  if (fill_missing_annot && !is.null(reference) && length(missing_idx) > 0) {
    filled <- parallel::mclapply(
      support_tbl$TCONS[missing_idx],
      function(x) {
        tryCatch(
          lookup_annot_tx(x, reference),
          error = function(e) NA_character_
        )
      },
      mc.cores = cores
    ) |> unlist()
    
    emp_anno[missing_idx] <- filled
  }
  
  support_tbl$emp_anno <- emp_anno[match(support_tbl$TCONS, names(emp_anno))]
  
  support_cols <- grep("^support", colnames(support_tbl))
  colnames(support_tbl)[support_cols] <- conditions
  
  support_tbl$gene_id <- ifelse(
    is.na(support_tbl$emp_anno),
    NA_character_,
    sub("\\|.*", "", support_tbl$emp_anno)
  )
  
  support_tbl$tx_id <- ifelse(
    is.na(support_tbl$emp_anno),
    NA_character_,
    sub(".*\\|", "", support_tbl$emp_anno)
  )
  
  support_tbl <- support_tbl[, c("TCONS", "gene_id", "tx_id", conditions)]
  
  if (!is.null(fpkm_mat)) {
    stopifnot(all(conditions %in% colnames(fpkm_mat)))
    
    fpkm_bool <- fpkm_mat[, conditions, drop = FALSE] > threshold
    support_tbl[, conditions] <- support_tbl[, conditions] & fpkm_bool
  }
  
  support_tbl
}

mapGeneName <- function(group_id, GTF) {
  gtf_df <- as.data.frame(GTF)
  map <- unique(gtf_df[, c("gene_id", "gene_name")])
  map$gene_id_base <- sub("\\.[0-9]+$", "", map$gene_id)
  group_id_base <- sub("\\.[0-9]+$", "", group_id)
  out <- map$gene_name[match(group_id_base, map$gene_id_base)]
  ifelse(is.na(out) | out == "", group_id, out)
}
