#' @title Plot the formation of a specific transcript
#' @param GTF A Granges object, extracted from the output of stringtieCombine{\code{\link{stringtieCombine}}},
#' filtered to rows with the type "exon". Use the \code{loadData} function to view the specific format.
#' @param geneName The gene name to which the transcript belongs.
#' @param TEname The TE element involved in the fusion.
#' @param txid The transcript ID of the TE-chimeric transcript to be plotted. 
#' @param rank Integer. The index of the exon in which the TE element is located in the chimeric event.
#' This information can be obtained from the \code{annotation} or the output of \code{\link{stringtieCombine}}.
#' @importFrom ggplot2 ggplot geom_rect geom_segment geom_text
#' @export
formPlot <- function(GTF, txid = NULL, rank = 1, geneName = "Gene", TEname = "MT2B2") {
  pic_table <- GTF[GTF$transcript_id == txid]
  if (length(pic_table) == 0) {
    print("The provided Transcript ID was not found in the GTF.")
    return()
  }
  N_exon <- length(pic_table)
  fill <- rep("#ECD1D6", N_exon)
  fill[rank] <- "#3A3B4F"
  picdata <- data.frame(
    x = seq(1, 1 * N_exon, 1),
    y = rep(0.5, N_exon),
    width = rep(0.5, N_exon),
    height = rep(0.1, N_exon),
    fill = fill
  )
  p <- ggplot(picdata) +
    geom_rect(aes(xmin = x - (width / 2), xmax = x + (width / 2),
                  ymin = y - (height / 2), ymax = y + (height / 2)),
              fill = fill, color = "black") +
    xlim(0, N_exon + 1) + ylim(0, 1) +
    theme_void()
  
  if (N_exon > 1) {
    median <- (picdata$x[1:(N_exon - 1)] + picdata$x[2:N_exon]) / 2
    
    pic_segment_1 <- data.frame(
      x = picdata$x[1:(N_exon - 1)] + 0.25,
      xend = median,
      y = rep(0.55, N_exon - 1),
      yend = rep(0.6, N_exon - 1)
    )
    
    pic_segment_2 <- data.frame(
      x = median,
      xend = picdata$x[2:N_exon] - 0.25,
      y = rep(0.6, N_exon - 1),
      yend = rep(0.55, N_exon - 1)
    )
    
    p <- p + geom_segment(data = pic_segment_1,
                          aes(x = x,
                              y = y,
                              xend = xend,
                              yend = yend),
                          color = "black") +
      geom_segment(data = pic_segment_2,
                   aes(x = x,
                       y = y,
                       xend = xend,
                       yend = yend),
                   color = "black")
  } else {
    message("The selected transcript contains only one exon; no intron/link will be drawn.")
  }
  p <- p + geom_text(x = picdata$x[rank], y = 0.4, label = TEname,
                     color = "black")
  p <- p + geom_text(x = 0.7, y = 0.7, label = paste(geneName, txid, sep = ":"),
                     color = "black", hjust = 0)
  
  return(p)
}



#' @title Plot the gene model in the control and reference groups
#' @param count A data matrix of bin-based counts，extracted from the output of countAnno\code{\link{countAnno}}
#' @param conditions A factor vector indicating the conditions (e.g., control and reference) of each sample
#' @param annotation A Granges object for annotated transcripts
#' @param idx The index of the gene.
#' @param labels A character vector, containing labels for the control and reference groups.
#' @param gene_name The gene name.
#' @param Title The title of plot, e.g., gene name.
#' @param gtf Character or GRanges. Path to the annotated GTF generated by \code{\link{gffcompareAnno}}, 
#' or a GRanges object containing exon-level transcript structures, such as the output of \code{\link{extractGTF}}.
#' @param txid The transcript id of a specific transcript for the gene
#' @param chi_test DESeq2 object. The output from the ChimericDrivenTest, extracted by \code{\link{extractTest}}
#' @importFrom rtracklayer import
#' @importFrom SummarizedExperiment assay
#' @importFrom S4Vectors subjectHits
#' @importFrom GenomicRanges GRanges findOverlaps
#' @importFrom dplyr mutate
#' @importFrom ggplot2 ggplot
#' @importFrom DESeq2 DESeqDataSetFromMatrix vst
#' @importFrom IRanges start end
#' @export
#' 
diffBinPlot <- function(count,
                        conditions,
                        annotation,
                        idx,
                        labels,
                        Title,
                        gtf,
                        txid,
                        chi_test,
                        gene_name,
                        ...) {
  if (length(labels) != 2) {
    stop("'labels' must contain exactly two group names.")
  }
  if (length(conditions) != ncol(count)) {
    stop("Length of 'conditions' must match the number of columns in 'count'.")
  }
  conditions <- factor(conditions, levels = labels)
  if (any(is.na(conditions))) {
    stop("'labels' must match the group names in 'conditions'.")
  }
  dds <- DESeqDataSetFromMatrix(countData = count,
                                colData = data.frame(condition = conditions),
                                design = ~ condition)
  dds_vst <- vst(dds)
  count_vst <- assay(dds_vst)
  subcounts <- count_vst[idx,]
  #
  texty <- "Expression"
  linecolor <- "#ECD1D6"
  label <- paste0("E0",annotation[idx]$exonic_part)
  colors <- c("#9BB0CB", "#8c3837")
  #
  layout(matrix(c(1,1,2), nrow = 3))
  p <-plot.new()
  par(mar = c(0,5,3,2))
  p <-plot.window(xlim=c(0, 1), ylim=c(0, max(subcounts)+1))
  intervals<-(0:nrow(subcounts))/nrow(subcounts)
  middle <- (intervals[1:length(intervals)-1]+intervals[2:length(intervals)])/2
  label <- paste0("E0",seq_len(nrow(subcounts)))
  axis(1, at=middle, labels=label)
  axis(2)
  mtext(texty,side=2,line=1.8)
  result <- data.frame(
    untreat = rowMeans(subcounts[, conditions == labels[1], drop = FALSE]),
    treat   = rowMeans(subcounts[, conditions == labels[2], drop = FALSE])
  )
  abline(v=middle, lty="dotted", col="#ECD1D6")
  xflatsegEnd <- intervals[1:length(intervals)-1]+0.8*(1/nrow(subcounts))
  segments(x0 = intervals[1:length(intervals)-1],
           x1 = xflatsegEnd,
           y0 = result[,1],
           y1 = result[,1],
           col  = "#9BB0CB",
           lwd = 1.8)
  segments(x0 = intervals[1:length(intervals)-1],
           x1 = xflatsegEnd,
           y0 = result[,2],
           y1 = result[,2],
           col  = "#8c3837",
           lwd = 1.8)
  segments(x0 = xflatsegEnd[1:length(xflatsegEnd)-1],
           x1 = intervals[2:(length(intervals)-1)],
           y0 = result[1:(dim(result)[1]-1),1],
           y1 = result[2:dim(result)[1],1],
           col="#9BB0CB", 
           lty="dotted",
           lwd = 1.2) 
  segments(x0 = xflatsegEnd[1:length(xflatsegEnd)-1],
           x1 = intervals[2:(length(intervals)-1)],
           y0 = result[1:(dim(result)[1]-1),2],
           y1 = result[2:dim(result)[1],2],
           col="#8c3837", 
           lty="dotted",
           lwd = 1.2) 
  legend(
    "topright",
    legend = labels,
    fill = c("#9BB0CB", "#8c3837"),
    border = NA,
    bty = "n",
    cex = 0.8
  )
  #
  if (is.character(gtf)) {
    gtf <- rtracklayer::import.gff(gtf)
  } else if (!inherits(gtf, "GRanges")) {
    stop("gtf must be either a GTF file path or a GRanges object.")
  }
  if (!"geneName" %in% colnames(chi_test)) {
    if (!all(c("gene_id", "gene_name") %in% colnames(S4Vectors::mcols(gtf)))) {
      stop("gtf must contain gene_id and gene_name columns to map geneName.")
    }
    gene_map <- unique(data.frame(
      gene_id = gtf$gene_id,
      gene_name = gtf$gene_name,
      stringsAsFactors = FALSE
    ))
    chi_test$geneName <- gene_map$gene_name[match(chi_test$groupID, gene_map$gene_id)]
    missing <- is.na(chi_test$geneName) | chi_test$geneName == ""
    chi_test$geneName[missing] <- chi_test$groupID[missing]
  }
  form_GR <- gtf[gtf$transcript_id==txid,]
  form_GR <- form_GR[form_GR$type=="exon"]
  overlaps <- findOverlaps(form_GR,annotation[idx,])
  map_GR <- annotation[idx,][subjectHits(overlaps)]
  exonicparts <- as.data.frame(annotation)[idx,"exonic_part"]
  exonicCHI <- as.data.frame(annotation)[idx,"transposon"]
  tx_loc <- exonicparts[subjectHits(overlaps)]
  tx_CHI <- exonicCHI[subjectHits(overlaps)]
  names(tx_loc)<- tx_CHI
  subset <- chi_test[complete.cases(chi_test$geneName), ]
  sig_loc <- as.numeric(gsub(".*E0*(\\d+)$", "\\1", subset[subset$geneName == gene_name, "featureID"]))
  sig_x <- middle[sig_loc]
  sig_y <- result[sig_loc,2]+0.3
  TE_y <- result[sig_loc,2]-0.2
  points(sig_x, sig_y, pch = "*", cex = 1.5)
  text(sig_x, TE_y, sapply(strsplit(subset[subset$geneName == gene_name, "TEclass"], ","), function(x) (x[1])), cex = 0.5)
  #
  p <-plot.new()
  par(mar = par(mar = c(0,0,5,0)))
  starts <- start(map_GR)
  ends <- end(map_GR)
  widths <- ends - starts
  plot.window(xlim=c(0,2*sum(ends-starts)), ylim=c(0, 1))
  rango <- seq_len(length(starts))
  gaplength <- starts[2:length(starts)]-ends[1:(length(ends)-1)]
  scalegap <- gaplength/sum(gaplength)*sum(ends-starts)
  cum_width <- cumsum(widths)
  cum_gap <- cumsum(scalegap)
  scalestarts <- c(0,cum_width[1:length(cum_width)-1]+cum_gap)
  scaleends <- cum_width+c(0,cum_gap)
  scalemid <- (scaleends[1:length(scaleends)-1]+scalestarts[2:length(scalestarts)])/2
  col <- ifelse(tx_CHI!="none", "#ECD1D6", "#3A3B4F")
  rect(scalestarts[rango], 0.2, scaleends[rango], 0.8,col = col)
  segments(scaleends[1:length(scaleends)-1], 0.4, scalemid, 0.5)
  segments(scalemid, 0.5, scalestarts[2:length(scalestarts)], 0.4)
  text(x=sum(ends-starts),y=0.1,label = txid)
  scaleintervals <- intervals*2*sum(ends-starts)
  segments(x0 = 0.5*(scalestarts+scaleends),
           x1 = middle[tx_loc]*(2*sum(ends-starts)),
           y0 = 0.8,
           y1 = 1,
           lty="dotted")
  
}


#' Plot Isoform Expression Dynamics
#'
#' Plot the expression dynamics of isoforms across different developmental samples or conditions.
#'
#' @param combineSE A `SummarizedExperiment` object generated by `stringtieCombine()`.
#' @param txid Character vector. Transcript IDs to plot.
#' @param gene_name Optional character. Gene name shown in the plot title.
#' @param assay_name Character. Assay to use. Default is `"FPKM"`.
#' @param group Optional character vector used to average samples by group/stage.
#' Length must match the number of columns in the assay matrix.
#' @param group_order Optional character vector specifying plotting order of groups.
#' @param ratio Logical. If TRUE, plot expression ratio among selected transcripts.
#' @param cols Optional color vector for transcript lines. Can be named by transcript ID.
#' @param main Optional plot title. If `NULL`, generated from `gene_name`.
#' @param ylab Optional y-axis label.
#' @param lwd Line width.
#' @param pch Point type.
#' @param ... Additional arguments passed to `plot()`.
#'
#' @return Invisibly returns the matrix used for plotting.
#'
#' @importFrom SummarizedExperiment assay assayNames
#' @export
plotIsoformDynamics <- function(combineSE,
                                txid,
                                gene_name = NULL,
                                assay_name = "FPKM",
                                group = NULL,
                                group_order = NULL,
                                ratio = FALSE,
                                cols = NULL,
                                main = NULL,
                                ylab = NULL,
                                lwd = 1.2,
                                pch_size = 3) {
  if (!inherits(combineSE, "SummarizedExperiment")) {
    stop("combineSE must be a SummarizedExperiment object.")
  }
  
  if (!assay_name %in% SummarizedExperiment::assayNames(combineSE)) {
    stop("assay_name must be one of: ",
         paste(SummarizedExperiment::assayNames(combineSE), collapse = ", "))
  }
  
  mat <- SummarizedExperiment::assay(combineSE, assay_name)
  
  txid <- txid[txid %in% rownames(mat)]
  if (length(txid) == 0) {
    stop("None of the supplied txid values were found in combineSE.")
  }
  
  mat <- mat[txid, , drop = FALSE]
  
  if (!is.null(group)) {
    if (length(group) != ncol(mat)) {
      stop("Length of group must match the number of assay columns.")
    }
    
    group <- as.character(group)
    
    if (!is.null(group_order)) {
      group <- factor(group, levels = group_order)
    } else {
      group <- factor(group, levels = unique(group))
    }
    
    mat <- sapply(levels(group), function(g) {
      rowMeans(mat[, group == g, drop = FALSE], na.rm = TRUE)
    })
    
    mat <- as.matrix(mat)
    rownames(mat) <- txid
    colnames(mat) <- levels(group)
  }
  
  if (isTRUE(ratio)) {
    mat <- sweep(mat, 2, colSums(mat, na.rm = TRUE), "/")
  }
  
  if (is.null(ylab)) {
    ylab <- if (isTRUE(ratio)) "Isoform Expression Ratio" else assay_name
  }
  
  if (is.null(main)) {
    main <- if (!is.null(gene_name)) {
      paste0(gene_name, " isoform ", ifelse(ratio, "ratio across stages", "expression"))
    } else {
      paste0("Transcript ", ifelse(ratio, "ratio", "expression"))
    }
  }
  
  df <- as.data.frame(mat)
  df$txid <- rownames(df)
  
  df_long <- tidyr::pivot_longer(
    df,
    cols = -txid,
    names_to = "stage",
    values_to = "value"
  )
  
  if (!is.null(group_order)) {
    df_long$stage <- factor(df_long$stage, levels = group_order)
  } else {
    df_long$stage <- factor(df_long$stage, levels = colnames(mat))
  }
  
  if (is.null(cols)) {
    cols <- c("#de7b60", "#3c415e", "#8c3837", "#383867")
  }
  
  if (!is.null(names(cols))) {
    cols <- cols[unique(df_long$txid)]
  } else {
    cols <- rep(cols, length.out = length(unique(df_long$txid)))
    names(cols) <- unique(df_long$txid)
  }
  
  p <- ggplot2::ggplot(
    df_long,
    ggplot2::aes(x = stage, y = value, group = txid, color = txid)
  ) +
    ggplot2::geom_line(linewidth = lwd) +
    ggplot2::geom_point(size = pch_size) +
    ggplot2::scale_color_manual(values = cols) +
    ggplot2::labs(
      title = main,
      x = "Developmental Stage",
      y = ylab,
      color = "Isoform Type"
    ) +
    ggplot2::theme_minimal(base_size = 14) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(hjust = 0, size = 18),
      axis.text.x = ggplot2::element_text(angle = 0, hjust = 0.5),
      legend.position = "right",
      legend.title = ggplot2::element_text(size = 14),
      legend.text = ggplot2::element_text(size = 12)
    )
  
  if (isTRUE(ratio)) {
    p <- p + ggplot2::scale_y_continuous(limits = c(0, 1))
  }
  
  return(p)
}


#' @title Plot TE position within a transcript structure
#'
#' @param GTF A GRanges object containing the complete transcript annotation.
#' @param TEposition A GRanges object returned by \code{\link{annotateTEPosition}}.
#' @param txid Character. Transcript ID to plot.
#' @param geneName Character. Gene name. If NULL, inferred from GTF.
#' @param showTElabel Logical. Whether to show TE labels.
#' @param clusterGap Numeric. Maximum plotting distance between adjacent TE
#'   segments to group them into the same visual cluster.
#' @param exonFill Character. Fill color for host-derived exon regions.
#' @param TEfill Character. Fill color for TE-derived regions.
#' @param borderColor Character. Color for exon borders, introns, and label lines.
#' @param TEborderColor Character. Border color separating adjacent TE segments.
#'
#' @return A ggplot object.
#'
#' @importFrom ggplot2 ggplot aes geom_rect geom_segment geom_text annotate
#'   coord_cartesian theme_void
#' @export
formTEPositionPlot <- function(
    GTF,
    TEposition,
    txid,
    geneName = NULL,
    showTElabel = TRUE,
    clusterGap = 0.015,
    exonFill = "#ECD1D6",
    TEfill = "#3A3B4F",
    borderColor = "black",
    TEborderColor = "white"
) {
  tx <- GTF[GTF$transcript_id == txid]
  
  if ("type" %in% names(S4Vectors::mcols(tx))) {
    tx <- tx[tx$type == "exon"]
  }
  
  if (!length(tx)) {
    stop("The provided transcript ID was not found in the GTF.")
  }
  
  txStrand <- unique(as.character(GenomicRanges::strand(tx)))
  
  if (length(txStrand) != 1L || txStrand == "*") {
    stop("Transcript strand could not be uniquely determined.")
  }
  
  ord <- if (txStrand == "+") {
    order(IRanges::start(tx))
  } else {
    order(IRanges::start(tx), decreasing = TRUE)
  }
  tx <- tx[ord]
  
  exonWidth <- 0.72
  exonX <- seq_along(tx)
  
  exonDf <- data.frame(
    exonId = exonX,
    seqnames = as.character(GenomicRanges::seqnames(tx)),
    start = IRanges::start(tx),
    end = IRanges::end(tx),
    strand = as.character(GenomicRanges::strand(tx)),
    x = exonX,
    xmin = exonX - exonWidth / 2,
    xmax = exonX + exonWidth / 2
  )
  
  exonDf$key <- paste(
    exonDf$seqnames, exonDf$start, exonDf$end, exonDf$strand,
    sep = ":"
  )
  
  if (is.null(geneName)) {
    geneName <- if ("gene_name" %in% names(S4Vectors::mcols(tx))) {
      unique(as.character(tx$gene_name))[1]
    } else {
      "Gene"
    }
  }
  
  p <- ggplot2::ggplot() +
    ggplot2::geom_rect(
      data = exonDf,
      ggplot2::aes(xmin = xmin, xmax = xmax, ymin = 0.45, ymax = 0.55),
      fill = exonFill,
      color = borderColor,
      linewidth = 0.45
    )
  
  if (nrow(exonDf) > 1L) {
    intronDf <- data.frame(
      x = exonDf$xmax[-nrow(exonDf)],
      xend = exonDf$xmin[-1]
    ) |>
      dplyr::mutate(mid = (x + xend) / 2)
    
    p <- p +
      ggplot2::geom_segment(
        data = intronDf,
        ggplot2::aes(x = x, xend = mid, y = 0.5, yend = 0.60),
        color = borderColor,
        linewidth = 0.45
      ) +
      ggplot2::geom_segment(
        data = intronDf,
        ggplot2::aes(x = mid, xend = xend, y = 0.60, yend = 0.5),
        color = borderColor,
        linewidth = 0.45
      )
  }
  
  teDf <- as.data.frame(
    TEposition[TEposition$transcript_id == txid]
  )
  
  if (nrow(teDf)) {
    teDf <- teDf |>
      dplyr::distinct(
        seqnames, start, end, strand,
        TE_start, TE_end, TE_name,
        .keep_all = TRUE
      )
    
    teDf$key <- paste(
      teDf$seqnames, teDf$start, teDf$end, teDf$strand,
      sep = ":"
    )
    
    teDf$exonId <- match(teDf$key, exonDf$key)
    teDf <- teDf[!is.na(teDf$exonId), , drop = FALSE]
  }
  
  if (nrow(teDf)) {
    teDf$ovStart <- pmax(teDf$start, teDf$TE_start)
    teDf$ovEnd <- pmin(teDf$end, teDf$TE_end)
    exonLen <- teDf$end - teDf$start + 1L
    
    fracStart <- if (txStrand == "+") {
      (teDf$ovStart - teDf$start) / exonLen
    } else {
      (teDf$end - teDf$ovEnd) / exonLen
    }
    
    fracEnd <- if (txStrand == "+") {
      (teDf$ovEnd - teDf$start + 1L) / exonLen
    } else {
      (teDf$end - teDf$ovStart + 1L) / exonLen
    }
    
    teDf$xmin <- exonDf$xmin[teDf$exonId] + fracStart * exonWidth
    teDf$xmax <- exonDf$xmin[teDf$exonId] + fracEnd * exonWidth
    
    p <- p +
      ggplot2::geom_rect(
        data = teDf,
        ggplot2::aes(xmin = xmin, xmax = xmax, ymin = 0.45, ymax = 0.55),
        fill = TEfill,
        color = TEborderColor,
        linewidth = 0.45
      )
    
    if (showTElabel) {
      labelDf <- teDf |>
        dplyr::group_by(exonId) |>
        dplyr::arrange(xmin, xmax, .by_group = TRUE) |>
        dplyr::mutate(
          previousEnd = dplyr::lag(cummax(xmax), default = -Inf),
          cluster = cumsum(xmin > previousEnd + clusterGap)
        ) |>
        dplyr::group_by(exonId, cluster) |>
        dplyr::summarise(
          clusterXmin = min(xmin),
          clusterXmax = max(xmax),
          TElabel = paste(unique(TE_name), collapse = ", "),
          .groups = "drop"
        ) |>
        dplyr::mutate(TEmid = (clusterXmin + clusterXmax) / 2) |>
        dplyr::group_by(exonId) |>
        dplyr::arrange(TEmid, .by_group = TRUE) |>
        dplyr::mutate(
          labelId = dplyr::row_number(),
          labelTop = labelId %% 2L == 1L,
          labelY = ifelse(labelTop, 0.76, 0.24),
          elbowY = ifelse(labelTop, 0.68, 0.32),
          anchorY = ifelse(labelTop, 0.55, 0.45)
        ) |>
        dplyr::ungroup()
      
      p <- p +
        ggplot2::geom_segment(
          data = labelDf,
          ggplot2::aes(
            x = TEmid, xend = TEmid,
            y = anchorY, yend = elbowY
          ),
          color = borderColor,
          linewidth = 0.3
        ) +
        ggplot2::geom_text(
          data = labelDf,
          ggplot2::aes(x = TEmid, y = labelY, label = TElabel),
          size = 3
        )
    }
  }
  
  p +
    ggplot2::geom_text(
      data = exonDf,
      ggplot2::aes(x = x, y = 0.62, label = paste0("E", exonId)),
      fontface = "bold",
      size = 3.4
    ) +
    ggplot2::annotate(
      "text",
      x = 0.55,
      y = 0.92,
      label = paste(geneName, txid, sep = ":"),
      hjust = 0,
      size = 4
    ) +
    ggplot2::coord_cartesian(
      xlim = c(0.35, length(tx) + 0.65),
      ylim = c(0.12, 0.98),
      clip = "off"
    ) +
    ggplot2::theme_void()
}